import {
  Category,
  Color,
  CompanySettings,
  Customer,
  Order,
  Product,
  Quote,
  Size,
  User,
  ActivityLog,
} from './types';

export const INITIAL_SETTINGS: CompanySettings = {
  id: 'settings-1',
  companyName: 'M2MBrasil Produtos Personalizados',
  tradeName: 'M2MBrasil',
  cnpj: '38.452.910/0001-84',
  logoUrl: '',
  phone: '(15) 99601-9227',
  whatsapp: '5515996019227',
  whatsappCountryCode: '55',
  whatsappAreaCode: '15',
  whatsappNumber: '996019227',
  whatsappDefaultMessage:
    'Olá, M2MBrasil! Gostaria de mais informações sobre produtos personalizados e orçamentos.',
  email: 'contato@m2mbrasil.com.br',
  instagram: '@m2mbrasil.personalizados',
  facebook: 'fb.com/m2mbrasil',
  address: 'Av. Paulista, 1000 - Bela Vista',
  number: '1000',
  complement: 'Conjunto 42',
  neighborhood: 'Bela Vista',
  city: 'São Paulo',
  state: 'SP',
  zipCode: '01310-100',
  deliveryFeeDefault: 18.0,
  minOrderValueForFreeShipping: 250.0,
  freeShippingEnabled: true,
  pixKeyType: 'cnpj',
  pixKey: '38452910000184',
  pixReceiverName: 'M2MBrasil Personalizados Ltda',
  pixCity: 'São Paulo',
};

export const INITIAL_COLORS: Color[] = [
  { id: 'c-preto', name: 'Preto', hex: '#111827', active: true },
  { id: 'c-branco', name: 'Branco', hex: '#F9FAFB', active: true },
  { id: 'c-azul-royal', name: 'Azul Royal', hex: '#1D4ED8', active: true },
  { id: 'c-azul-marinho', name: 'Azul Marinho', hex: '#0F172A', active: true },
  { id: 'c-vermelho', name: 'Vermelho', hex: '#DC2626', active: true },
  { id: 'c-verde-bandeira', name: 'Verde Bandeira', hex: '#15803D', active: true },
  { id: 'c-verde-militar', name: 'Verde Militar', hex: '#4D7C0F', active: true },
  { id: 'c-amarelo', name: 'Amarelo Ouro', hex: '#EAB308', active: true },
  { id: 'c-rosa', name: 'Rosa Claro', hex: '#F472B6', active: true },
  { id: 'c-pink', name: 'Pink Neon', hex: '#DB2777', active: true },
  { id: 'c-lilas', name: 'Lilás', hex: '#A855F7', active: true },
  { id: 'c-cinza-mescla', name: 'Cinza Mescla', hex: '#94A3B8', active: true },
];

export const INITIAL_SIZES: Size[] = [
  { id: 's-infantil', name: 'Infantil', order: 1, active: true },
  { id: 's-p', name: 'P', order: 2, active: true },
  { id: 's-m', name: 'M', order: 3, active: true },
  { id: 's-g', name: 'G', order: 4, active: true },
  { id: 's-gg', name: 'GG', order: 5, active: true },
  { id: 's-g1', name: 'G1', order: 6, active: true },
  { id: 's-g2', name: 'G2', order: 7, active: true },
  { id: 's-g3', name: 'G3', order: 8, active: true },
  { id: 's-unico', name: 'Tamanho Único', order: 9, active: true },
];

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-camisetas',
    name: 'Camisetas & Dry Fit',
    slug: 'camisetas-dry-fit',
    description: 'Camisetas em tecido Dry Fit tecnológico, 100% Algodão e Poliviscose.',
    icon: 'Shirt',
    active: true,
    order: 1,
  },
  {
    id: 'cat-moletons',
    name: 'Moletons & Agasalhos',
    slug: 'moletons-agasalhos',
    description: 'Moletons flanelados canguru, gola careca e zíper com estampa de alta durabilidade.',
    icon: 'Layers',
    active: true,
    order: 2,
  },
  {
    id: 'cat-bones',
    name: 'Bonés & Acessórios',
    slug: 'bones-acessorios',
    description: 'Bonés trucker com tela respirável, bonés dad hat e aba reta personalizados.',
    icon: 'Sparkles',
    active: true,
    order: 3,
  },
  {
    id: 'cat-canecas',
    name: 'Canecas & Brindes',
    slug: 'canecas-brindes',
    description: 'Canecas de porcelana resinada, alumínio, copos térmicos e squeezer.',
    icon: 'Coffee',
    active: true,
    order: 4,
  },
  {
    id: 'cat-uniformes',
    name: 'Uniformes Empresariais',
    slug: 'uniformes-empresariais',
    description: 'Linha corporativa para equipes comerciais, operacionais e de eventos.',
    icon: 'Briefcase',
    active: true,
    order: 5,
  },
  {
    id: 'cat-polo-babylook',
    name: 'Camisas Polo & Baby Look',
    slug: 'camisas-polo-baby-look',
    description: 'Polos em piquet premium e baby looks com modelagem ajustada.',
    icon: 'Tag',
    active: true,
    order: 6,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    code: 'DRY-001',
    name: 'Camiseta Personalizada Dry Fit UV50+',
    slug: 'camiseta-personalizada-dry-fit-uv50',
    categoryId: 'cat-camisetas',
    categoryName: 'Camisetas & Dry Fit',
    shortDescription: 'Tecido respirável de secagem rápida com proteção UV50+ ideal para esportes e equipes.',
    description:
      'A Camiseta Personalizada Dry Fit da M2MBrasil é produzida em malha tecnológica 100% poliéster com tratamento antibacteriano e proteção solar UV50+. Permite estampas em sublimação total de alta nitidez que não desbotam nem trincam. Perfeita para academias, eventos esportivos, maratonas, equipes de corrida e uniformes leves.',
    price: 39.9,
    promotionalPrice: 34.9,
    cost: 16.5,
    minQuantity: 1,
    stock: 250,
    active: true,
    featured: true,
    isPromotion: true,
    images: [
      {
        id: 'img-1-1',
        productId: 'prod-1',
        url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
        isPrimary: true,
        order: 1,
        caption: 'Frente Azul Royal',
      },
      {
        id: 'img-1-2',
        productId: 'prod-1',
        url: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=800&q=80',
        isPrimary: false,
        order: 2,
        caption: 'Preta em detalhe',
      },
      {
        id: 'img-1-3',
        productId: 'prod-1',
        url: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=800&q=80',
        isPrimary: false,
        order: 3,
        caption: 'Branca clássica',
      },
    ],
    availableColors: [
      INITIAL_COLORS[0], // Preto
      INITIAL_COLORS[1], // Branco
      INITIAL_COLORS[2], // Azul Royal
      INITIAL_COLORS[4], // Vermelho
      INITIAL_COLORS[5], // Verde Bandeira
    ],
    availableSizes: [
      INITIAL_SIZES[1], // P
      INITIAL_SIZES[2], // M
      INITIAL_SIZES[3], // G
      INITIAL_SIZES[4], // GG
      INITIAL_SIZES[5], // G1
    ],
    variants: [
      {
        id: 'v-1-1',
        productId: 'prod-1',
        colorId: 'c-azul-royal',
        colorName: 'Azul Royal',
        colorHex: '#1D4ED8',
        sizeId: 's-m',
        sizeName: 'M',
        sku: 'DRY-ROY-M',
        price: 34.9,
        stock: 50,
        available: true,
      },
      {
        id: 'v-1-2',
        productId: 'prod-1',
        colorId: 'c-azul-royal',
        colorName: 'Azul Royal',
        colorHex: '#1D4ED8',
        sizeId: 's-g',
        sizeName: 'G',
        sku: 'DRY-ROY-G',
        price: 34.9,
        stock: 60,
        available: true,
      },
      {
        id: 'v-1-3',
        productId: 'prod-1',
        colorId: 'c-preto',
        colorName: 'Preto',
        colorHex: '#111827',
        sizeId: 's-m',
        sizeName: 'M',
        sku: 'DRY-BLK-M',
        price: 34.9,
        stock: 45,
        available: true,
      },
      {
        id: 'v-1-4',
        productId: 'prod-1',
        colorId: 'c-preto',
        colorName: 'Preto',
        colorHex: '#111827',
        sizeId: 's-g',
        sizeName: 'G',
        sku: 'DRY-BLK-G',
        price: 34.9,
        stock: 55,
        available: true,
      },
    ],
    allowCustomization: true,
    customizationLocations: ['frente', 'costas', 'peito_esquerdo', 'manga_esquerda', 'manga_direita'],
    createdAt: '2026-08-01T10:00:00.000Z',
    updatedAt: '2026-08-18T14:30:00.000Z',
  },
  {
    id: 'prod-2',
    code: 'MOL-002',
    name: 'Moletom Canguru Premium Flanelado com Capuz',
    slug: 'moletom-canguru-premium-flanelado-capuz',
    categoryId: 'cat-moletons',
    categoryName: 'Moletons & Agasalhos',
    shortDescription: 'Moletom encorpado 3 cabos 50% algodão 50% poliéster, interior flanelado macio e bolso frontal.',
    description:
      'O Moletom Canguru M2MBrasil é confeccionado em tecido 3 cabos de altíssima gramatura (320g/m²), garantindo proteção térmica superior e acabamento requintado. Possui capuz forrado com ilhós e cordão regulador, punhos e barra em ribana elástica e bolso frontal canguru. Suporta bordado de precisão ou estampa silk digital DTF de alta definição.',
    price: 89.9,
    promotionalPrice: 84.9,
    cost: 44.0,
    minQuantity: 1,
    stock: 140,
    active: true,
    featured: true,
    isPromotion: false,
    images: [
      {
        id: 'img-2-1',
        productId: 'prod-2',
        url: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
        isPrimary: true,
        order: 1,
        caption: 'Moletom Cinza Mescla',
      },
      {
        id: 'img-2-2',
        productId: 'prod-2',
        url: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?auto=format&fit=crop&w=800&q=80',
        isPrimary: false,
        order: 2,
        caption: 'Moletom Preto',
      },
    ],
    availableColors: [
      INITIAL_COLORS[0], // Preto
      INITIAL_COLORS[3], // Azul Marinho
      INITIAL_COLORS[4], // Vermelho
      INITIAL_COLORS[11], // Cinza Mescla
    ],
    availableSizes: [
      INITIAL_SIZES[1], // P
      INITIAL_SIZES[2], // M
      INITIAL_SIZES[3], // G
      INITIAL_SIZES[4], // GG
      INITIAL_SIZES[5], // G1
    ],
    variants: [
      {
        id: 'v-2-1',
        productId: 'prod-2',
        colorId: 'c-preto',
        colorName: 'Preto',
        colorHex: '#111827',
        sizeId: 's-m',
        sizeName: 'M',
        sku: 'MOL-BLK-M',
        price: 89.9,
        stock: 30,
        available: true,
      },
      {
        id: 'v-2-2',
        productId: 'prod-2',
        colorId: 'c-cinza-mescla',
        colorName: 'Cinza Mescla',
        colorHex: '#94A3B8',
        sizeId: 's-g',
        sizeName: 'G',
        sku: 'MOL-GRY-G',
        price: 89.9,
        stock: 35,
        available: true,
      },
    ],
    allowCustomization: true,
    customizationLocations: ['frente', 'costas', 'peito_esquerdo'],
    createdAt: '2026-08-02T11:00:00.000Z',
    updatedAt: '2026-08-17T16:00:00.000Z',
  },
  {
    id: 'prod-3',
    code: 'BON-003',
    name: 'Boné Trucker Personalizado Americano com Tela',
    slug: 'bone-trucker-personalizado-americano-tela',
    categoryId: 'cat-bones',
    categoryName: 'Bonés & Acessórios',
    shortDescription: 'Boné modelo Trucker com frente espumada, tela traseira respirável e fecho snapback ajustável.',
    description:
      'O clássico Boné Trucker da M2MBrasil possui copa estruturada com entretela importada, aba curva com 4 costuras reforçadas e regulagem snapback em PVC resistente. Frente em tecido 100% poliéster próprio para silk, sublimação ou aplique bordado termocolante.',
    price: 35.0,
    promotionalPrice: 29.9,
    cost: 14.0,
    minQuantity: 1,
    stock: 300,
    active: true,
    featured: true,
    isPromotion: true,
    images: [
      {
        id: 'img-3-1',
        productId: 'prod-3',
        url: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&w=800&q=80',
        isPrimary: true,
        order: 1,
        caption: 'Boné Trucker Frontal',
      },
      {
        id: 'img-3-2',
        productId: 'prod-3',
        url: 'https://images.unsplash.com/photo-1575428652377-a2d80e2277fc?auto=format&fit=crop&w=800&q=80',
        isPrimary: false,
        order: 2,
        caption: 'Boné com detalhes',
      },
    ],
    availableColors: [
      INITIAL_COLORS[0], // Preto
      INITIAL_COLORS[1], // Branco
      INITIAL_COLORS[2], // Azul Royal
      INITIAL_COLORS[4], // Vermelho
    ],
    availableSizes: [
      INITIAL_SIZES[8], // Tamanho Único
    ],
    variants: [
      {
        id: 'v-3-1',
        productId: 'prod-3',
        colorId: 'c-preto',
        colorName: 'Preto',
        colorHex: '#111827',
        sizeId: 's-unico',
        sizeName: 'Tamanho Único',
        sku: 'BON-TRK-BLK',
        price: 29.9,
        stock: 120,
        available: true,
      },
    ],
    allowCustomization: true,
    customizationLocations: ['frente'],
    createdAt: '2026-08-03T09:30:00.000Z',
    updatedAt: '2026-08-16T12:00:00.000Z',
  },
  {
    id: 'prod-4',
    code: 'CAN-004',
    name: 'Caneca de Cerâmica Resinada Alto Brilho 325ml',
    slug: 'caneca-ceramica-resinada-alto-brilho-325ml',
    categoryId: 'cat-canecas',
    categoryName: 'Canecas & Brindes',
    shortDescription: 'Caneca de cerâmica AAA com resina ultra-brilhante para personalização fotográfica sem limites.',
    description:
      'Caneca de cerâmica classe AAA com parede espessa de alta retenção de temperatura, alça ergonômica e acabamento resinado especial. Permite estampa em qualidade fotográfica 360° com cores vivas e resistência a micro-ondas e lava-louças. O brinde perfeito para datas comemorativas, aniversários e brindes corporativos.',
    price: 24.9,
    promotionalPrice: 22.9,
    cost: 9.8,
    minQuantity: 1,
    stock: 450,
    active: true,
    featured: true,
    isPromotion: false,
    images: [
      {
        id: 'img-4-1',
        productId: 'prod-4',
        url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
        isPrimary: true,
        order: 1,
        caption: 'Caneca Branca Resinada',
      },
      {
        id: 'img-4-2',
        productId: 'prod-4',
        url: 'https://images.unsplash.com/photo-1577937927133-66ef06acdf18?auto=format&fit=crop&w=800&q=80',
        isPrimary: false,
        order: 2,
        caption: 'Caneca com café',
      },
    ],
    availableColors: [
      INITIAL_COLORS[1], // Branco
      INITIAL_COLORS[0], // Preto
      INITIAL_COLORS[2], // Azul Royal
    ],
    availableSizes: [
      INITIAL_SIZES[8], // Único
    ],
    variants: [
      {
        id: 'v-4-1',
        productId: 'prod-4',
        colorId: 'c-branco',
        colorName: 'Branco',
        colorHex: '#F9FAFB',
        sizeId: 's-unico',
        sizeName: '325ml',
        sku: 'CAN-CER-WHT',
        price: 22.9,
        stock: 300,
        available: true,
      },
    ],
    allowCustomization: true,
    customizationLocations: ['frente', 'costas'],
    createdAt: '2026-08-04T14:15:00.000Z',
    updatedAt: '2026-08-18T10:00:00.000Z',
  },
  {
    id: 'prod-5',
    code: 'POLO-005',
    name: 'Camisa Polo Piquet Premium Bordada / Estampada',
    slug: 'camisa-polo-piquet-premium-bordada',
    categoryId: 'cat-polo-babylook',
    categoryName: 'Camisas Polo & Baby Look',
    shortDescription: 'Polo em malha piquet 50% algodão 50% poliéster, gola e punhos com friso fino e botões combinando.',
    description:
      'A Polo Corporativa M2MBrasil é a escolha perfeita para vestir sua equipe com elegância e profissionalismo. Tecido piquet pré-encolhido que não amassa facilmente e mantém o caimento impecável durante todo o dia. Gola reforçada que não enrola.',
    price: 54.9,
    promotionalPrice: 49.9,
    cost: 24.0,
    minQuantity: 1,
    stock: 180,
    active: true,
    featured: false,
    isPromotion: false,
    images: [
      {
        id: 'img-5-1',
        productId: 'prod-5',
        url: 'https://images.unsplash.com/photo-1625910513413-742217c49045?auto=format&fit=crop&w=800&q=80',
        isPrimary: true,
        order: 1,
        caption: 'Polo Marinho',
      },
    ],
    availableColors: [
      INITIAL_COLORS[0], // Preto
      INITIAL_COLORS[1], // Branco
      INITIAL_COLORS[2], // Azul Royal
      INITIAL_COLORS[3], // Azul Marinho
    ],
    availableSizes: [
      INITIAL_SIZES[1], // P
      INITIAL_SIZES[2], // M
      INITIAL_SIZES[3], // G
      INITIAL_SIZES[4], // GG
    ],
    variants: [],
    allowCustomization: true,
    customizationLocations: ['peito_esquerdo', 'costas', 'manga_direita'],
    createdAt: '2026-08-05T08:00:00.000Z',
    updatedAt: '2026-08-15T11:00:00.000Z',
  },
  {
    id: 'prod-6',
    code: 'UNIF-006',
    name: 'Conjunto Uniforme Empresarial Ripstop / Brim Leve',
    slug: 'conjunto-uniforme-empresarial-ripstop-brim',
    categoryId: 'cat-uniformes',
    categoryName: 'Uniformes Empresariais',
    shortDescription: 'Conjunto camisa polo/técnica + calça profissional em brim pesado com reforço nos joelhos.',
    description:
      'Uniformes completos de alta resistência para operações, logística, manutenção e fábricas. Confeccionados com costuras duplas travadas, faixa refletiva de alta visibilidade opcional e tecido tratado contra desbotamento por lavagens industriais contínuas.',
    price: 119.9,
    promotionalPrice: 109.9,
    cost: 58.0,
    minQuantity: 5,
    stock: 90,
    active: true,
    featured: false,
    isPromotion: false,
    images: [
      {
        id: 'img-6-1',
        productId: 'prod-6',
        url: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=800&q=80',
        isPrimary: true,
        order: 1,
        caption: 'Conjunto Operacional',
      },
    ],
    availableColors: [
      INITIAL_COLORS[0], // Preto
      INITIAL_COLORS[3], // Azul Marinho
      INITIAL_COLORS[6], // Verde Militar
    ],
    availableSizes: [
      INITIAL_SIZES[1], // P
      INITIAL_SIZES[2], // M
      INITIAL_SIZES[3], // G
      INITIAL_SIZES[4], // GG
      INITIAL_SIZES[5], // G1
    ],
    variants: [],
    allowCustomization: true,
    customizationLocations: ['frente', 'costas', 'peito_esquerdo'],
    createdAt: '2026-08-06T15:00:00.000Z',
    updatedAt: '2026-08-16T18:00:00.000Z',
  },
  {
    id: 'prod-7',
    code: 'BABY-007',
    name: 'Baby Look Feminina 100% Algodão Penteado 30.1',
    slug: 'baby-look-feminina-100-algodao-penteado',
    categoryId: 'cat-polo-babylook',
    categoryName: 'Camisas Polo & Baby Look',
    shortDescription: 'Modelagem feminina acinturada, toque macio e acabamento com costura pespontada.',
    description:
      'A Baby Look M2MBrasil é produzida em algodão penteado fio 30.1 de primeira linha, proporcionando toque suave na pele e caimento confortável. Ideal para equipes de atendimento, eventos corporativos e coleções de marca própria.',
    price: 36.9,
    promotionalPrice: 32.9,
    cost: 15.0,
    minQuantity: 1,
    stock: 160,
    active: true,
    featured: false,
    isPromotion: true,
    images: [
      {
        id: 'img-7-1',
        productId: 'prod-7',
        url: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=800&q=80',
        isPrimary: true,
        order: 1,
        caption: 'Baby Look Branca',
      },
    ],
    availableColors: [
      INITIAL_COLORS[0], // Preto
      INITIAL_COLORS[1], // Branco
      INITIAL_COLORS[8], // Rosa
      INITIAL_COLORS[9], // Pink
      INITIAL_COLORS[10], // Lilás
    ],
    availableSizes: [
      INITIAL_SIZES[1], // P
      INITIAL_SIZES[2], // M
      INITIAL_SIZES[3], // G
      INITIAL_SIZES[4], // GG
    ],
    variants: [],
    allowCustomization: true,
    customizationLocations: ['frente', 'costas', 'peito_esquerdo'],
    createdAt: '2026-08-07T12:00:00.000Z',
    updatedAt: '2026-08-17T09:00:00.000Z',
  },
  {
    id: 'prod-8',
    code: 'CHOPP-008',
    name: 'Caneca de Chopp Vidro Jateado 475ml',
    slug: 'caneca-chopp-vidro-jateado-475ml',
    categoryId: 'cat-canecas',
    categoryName: 'Canecas & Brindes',
    shortDescription: 'Caneca de chopp em vidro pesado jateado fosco especial para freezer e chopp trincando.',
    description:
      'Caneca de chopp clássica com fundo grosso e textura jateada aveludada. Mantém a cerveja gelada por mais tempo quando colocada no congelador. Personalização durável por sublimação de alta temperatura.',
    price: 42.0,
    promotionalPrice: 38.0,
    cost: 18.5,
    minQuantity: 1,
    stock: 210,
    active: true,
    featured: true,
    isPromotion: false,
    images: [
      {
        id: 'img-8-1',
        productId: 'prod-8',
        url: 'https://images.unsplash.com/photo-1538220856186-0be0e085984d?auto=format&fit=crop&w=800&q=80',
        isPrimary: true,
        order: 1,
        caption: 'Caneca Chopp Jateada',
      },
    ],
    availableColors: [
      INITIAL_COLORS[1], // Branco / Transparente
    ],
    availableSizes: [
      INITIAL_SIZES[8], // Único
    ],
    variants: [],
    allowCustomization: true,
    customizationLocations: ['frente', 'costas'],
    createdAt: '2026-08-08T16:00:00.000Z',
    updatedAt: '2026-08-18T15:00:00.000Z',
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-admin-mauricio',
    name: 'Maurício Mastorillo (Admin)',
    email: 'MauricioM2M',
    password: '78645524',
    role: 'admin',
    phone: '(15) 99601-9227',
    createdAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'usr-cust-1',
    name: 'Carlos Eduardo Silveira',
    email: 'cliente@m2mbrasil.com.br',
    password: 'cliente123',
    role: 'customer',
    phone: '(11) 97123-4567',
    createdAt: '2026-08-10T11:20:00.000Z',
  },
  {
    id: 'usr-cust-2',
    name: 'Ana Paula Rocha (Academia IronFit)',
    email: 'anapaula@ironfit.com.br',
    password: 'cliente123',
    role: 'customer',
    phone: '(11) 96543-2109',
    createdAt: '2026-08-12T14:10:00.000Z',
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    userId: 'usr-cust-1',
    code: 'CLI-000101',
    name: 'Carlos Eduardo Silveira',
    cpfCnpj: '284.912.488-30',
    phone: '(11) 97123-4567',
    whatsapp: '11971234567',
    email: 'cliente@m2mbrasil.com.br',
    zipCode: '04571-010',
    address: 'Rua Funchal',
    number: '418',
    complement: 'Apto 102',
    neighborhood: 'Vila Olímpia',
    city: 'São Paulo',
    state: 'SP',
    notes: 'Cliente corporativo frequente. Prefere estampas discretas em silk DTF.',
    createdAt: '2026-08-10T11:20:00.000Z',
    totalSpent: 428.8,
    ordersCount: 2,
  },
  {
    id: 'cust-2',
    userId: 'usr-cust-2',
    code: 'CLI-000102',
    name: 'Ana Paula Rocha (Academia IronFit)',
    cpfCnpj: '41.892.109/0001-92',
    phone: '(11) 96543-2109',
    whatsapp: '11965432109',
    email: 'anapaula@ironfit.com.br',
    zipCode: '01414-001',
    address: 'Alameda Santos',
    number: '1200',
    neighborhood: 'Cerqueira César',
    city: 'São Paulo',
    state: 'SP',
    notes: 'Pedidos em lotes de camisetas Dry Fit para professores e eventos da academia.',
    createdAt: '2026-08-12T14:10:00.000Z',
    totalSpent: 1396.0,
    ordersCount: 1,
  },
  {
    id: 'cust-3',
    code: 'CLI-000103',
    name: 'Mariana Costa Guimarães',
    cpfCnpj: '391.820.449-01',
    phone: '(21) 98877-6655',
    whatsapp: '21988776655',
    email: 'mariana.costa@gmail.com',
    zipCode: '22041-001',
    address: 'Avenida Atlântica',
    number: '2800',
    complement: 'Bloco B 504',
    neighborhood: 'Copacabana',
    city: 'Rio de Janeiro',
    state: 'RJ',
    notes: 'Solicitou orçamento para brindes de casamento (canecas e bonés).',
    createdAt: '2026-08-15T09:40:00.000Z',
    totalSpent: 0,
    ordersCount: 0,
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-101',
    orderNumber: 'PED-000101',
    customerId: 'cust-1',
    customerName: 'Carlos Eduardo Silveira',
    customerPhone: '(11) 97123-4567',
    customerWhatsapp: '11971234567',
    customerEmail: 'cliente@m2mbrasil.com.br',
    customerCpfCnpj: '284.912.488-30',
    shippingAddress: {
      zipCode: '04571-010',
      address: 'Rua Funchal',
      number: '418',
      complement: 'Apto 102',
      neighborhood: 'Vila Olímpia',
      city: 'São Paulo',
      state: 'SP',
    },
    items: [
      {
        id: 'item-101-1',
        productId: 'prod-1',
        productName: 'Camiseta Personalizada Dry Fit UV50+',
        productImage: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=400&q=80',
        colorName: 'Preto',
        colorHex: '#111827',
        sizeName: 'G',
        quantity: 3,
        unitPrice: 34.9,
        subtotal: 104.7,
        customization: {
          customText: 'SILVEIRA RUNNERS',
          placement: 'Costas',
          notes: 'Logo pequeno no peito esquerdo e nome nas costas.',
        },
      },
      {
        id: 'item-101-2',
        productId: 'prod-3',
        productName: 'Boné Trucker Personalizado Americano com Tela',
        productImage: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&w=400&q=80',
        colorName: 'Preto',
        colorHex: '#111827',
        sizeName: 'Tamanho Único',
        quantity: 2,
        unitPrice: 29.9,
        subtotal: 59.8,
        customization: {
          customText: 'SR 2026',
          placement: 'Frente',
        },
      },
    ],
    subtotal: 164.5,
    discount: 10.0,
    shipping: 18.0,
    total: 172.5,
    paymentMethod: 'pix',
    paymentStatus: 'pago',
    status: 'em_producao',
    notes: 'Quero o logo pequeno no peito esquerdo e a estampa grande nas costas.',
    internalNotes: 'Arte aprovada pelo cliente no WhatsApp em 17/08. Tecido em corte.',
    timeline: [
      { status: 'novo', date: '2026-08-16T10:15:00.000Z', note: 'Pedido criado no site', user: 'Sistema' },
      { status: 'pagamento_confirmado', date: '2026-08-16T10:20:00.000Z', note: 'Pagamento via PIX confirmado automaticamente', user: 'Financeiro' },
      { status: 'arte_sendo_criada', date: '2026-08-16T14:00:00.000Z', note: 'Arte vetorizada para DTF', user: 'Designer' },
      { status: 'arte_aprovada', date: '2026-08-17T11:30:00.000Z', note: 'Aprovado pelo cliente via WhatsApp', user: 'Maurício (Admin)' },
      { status: 'em_producao', date: '2026-08-18T08:00:00.000Z', note: 'Enviado para estamparia e prensa', user: 'Produção' },
    ],
    createdAt: '2026-08-16T10:15:00.000Z',
    updatedAt: '2026-08-18T08:00:00.000Z',
  },
  {
    id: 'ord-102',
    orderNumber: 'PED-000102',
    customerId: 'cust-2',
    customerName: 'Ana Paula Rocha (Academia IronFit)',
    customerPhone: '(11) 96543-2109',
    customerWhatsapp: '11965432109',
    customerEmail: 'anapaula@ironfit.com.br',
    customerCpfCnpj: '41.892.109/0001-92',
    shippingAddress: {
      zipCode: '01414-001',
      address: 'Alameda Santos',
      number: '1200',
      neighborhood: 'Cerqueira César',
      city: 'São Paulo',
      state: 'SP',
    },
    items: [
      {
        id: 'item-102-1',
        productId: 'prod-1',
        productName: 'Camiseta Personalizada Dry Fit UV50+',
        productImage: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=400&q=80',
        colorName: 'Azul Royal',
        colorHex: '#1D4ED8',
        sizeName: 'M',
        quantity: 20,
        unitPrice: 34.9,
        subtotal: 698.0,
        customization: {
          customText: 'IRONFIT TEAM COACH',
          placement: 'Costas',
        },
      },
      {
        id: 'item-102-2',
        productId: 'prod-1',
        productName: 'Camiseta Personalizada Dry Fit UV50+',
        productImage: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=400&q=80',
        colorName: 'Azul Royal',
        colorHex: '#1D4ED8',
        sizeName: 'G',
        quantity: 20,
        unitPrice: 34.9,
        subtotal: 698.0,
        customization: {
          customText: 'IRONFIT TEAM COACH',
          placement: 'Costas',
        },
      },
    ],
    subtotal: 1396.0,
    discount: 50.0,
    shipping: 0.0,
    total: 1346.0,
    paymentMethod: 'pix',
    paymentStatus: 'pago',
    status: 'pronto',
    notes: 'Entregar na recepção da academia no horário das 09h às 18h.',
    internalNotes: 'Pedido finalizado na embalagem. Aguardando motoboy/retirada.',
    timeline: [
      { status: 'novo', date: '2026-08-13T09:00:00.000Z', note: 'Pedido registrado', user: 'Sistema' },
      { status: 'pagamento_confirmado', date: '2026-08-13T09:30:00.000Z', note: 'PIX 50% adiantado', user: 'Financeiro' },
      { status: 'arte_aprovada', date: '2026-08-14T10:00:00.000Z', note: 'Logo IronFit vetor aprovado', user: 'Admin' },
      { status: 'em_producao', date: '2026-08-15T08:00:00.000Z', note: 'Silk serigrafia executado', user: 'Produção' },
      { status: 'pronto', date: '2026-08-18T16:00:00.000Z', note: 'Embalado e conferido com 40 peças', user: 'Expedição' },
    ],
    createdAt: '2026-08-13T09:00:00.000Z',
    updatedAt: '2026-08-18T16:00:00.000Z',
  },
  {
    id: 'ord-103',
    orderNumber: 'PED-000103',
    customerId: 'cust-1',
    customerName: 'Carlos Eduardo Silveira',
    customerPhone: '(11) 97123-4567',
    customerWhatsapp: '11971234567',
    customerEmail: 'cliente@m2mbrasil.com.br',
    customerCpfCnpj: '284.912.488-30',
    shippingAddress: {
      zipCode: '04571-010',
      address: 'Rua Funchal',
      number: '418',
      complement: 'Apto 102',
      neighborhood: 'Vila Olímpia',
      city: 'São Paulo',
      state: 'SP',
    },
    items: [
      {
        id: 'item-103-1',
        productId: 'prod-2',
        productName: 'Moletom Canguru Premium Flanelado com Capuz',
        productImage: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=400&q=80',
        colorName: 'Cinza Mescla',
        colorHex: '#94A3B8',
        sizeName: 'G',
        quantity: 2,
        unitPrice: 84.9,
        subtotal: 169.8,
        customization: {
          customText: 'SILVEIRA DESIGN',
          placement: 'Peito Esquerdo',
        },
      },
      {
        id: 'item-103-2',
        productId: 'prod-4',
        productName: 'Caneca de Cerâmica Resinada Alto Brilho 325ml',
        productImage: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=400&q=80',
        colorName: 'Branco',
        colorHex: '#F9FAFB',
        sizeName: '325ml',
        quantity: 4,
        unitPrice: 22.9,
        subtotal: 91.6,
      },
    ],
    subtotal: 261.4,
    discount: 5.1,
    shipping: 0.0,
    total: 256.3,
    paymentMethod: 'cartao',
    paymentStatus: 'pago',
    status: 'entregue',
    notes: 'Deixar na portaria com o porteiro Silva.',
    timeline: [
      { status: 'novo', date: '2026-08-01T14:00:00.000Z', note: 'Pedido criado', user: 'Sistema' },
      { status: 'pagamento_confirmado', date: '2026-08-01T14:05:00.000Z', note: 'Cartão aprovado', user: 'Gateway' },
      { status: 'arte_aprovada', date: '2026-08-02T10:00:00.000Z', note: 'Arte aprovada', user: 'Cliente' },
      { status: 'em_producao', date: '2026-08-03T08:00:00.000Z', note: 'Produzido', user: 'Estamparia' },
      { status: 'pronto', date: '2026-08-04T15:00:00.000Z', note: 'Pronto para entrega', user: 'Expedição' },
      { status: 'enviado', date: '2026-08-05T09:00:00.000Z', note: 'Enviado por transportadora', user: 'Logística' },
      { status: 'entregue', date: '2026-08-06T14:30:00.000Z', note: 'Entregue com sucesso e assinado', user: 'Transportadora' },
    ],
    createdAt: '2026-08-01T14:00:00.000Z',
    updatedAt: '2026-08-06T14:30:00.000Z',
  },
];

export const INITIAL_QUOTES: Quote[] = [
  {
    id: 'orc-1',
    quoteNumber: 'ORC-000001',
    customerId: 'cust-3',
    customerName: 'Mariana Costa Guimarães',
    customerPhone: '(21) 98877-6655',
    customerWhatsapp: '21988776655',
    customerEmail: 'mariana.costa@gmail.com',
    items: [
      {
        id: 'qitem-1',
        productId: 'prod-4',
        productName: 'Caneca de Cerâmica Resinada Alto Brilho 325ml',
        productImage: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=400&q=80',
        colorName: 'Branco',
        colorHex: '#F9FAFB',
        sizeName: '325ml',
        quantity: 50,
        unitPrice: 19.9,
        subtotal: 995.0,
        customization: {
          customText: 'Mari & Lucas - 12.12.2026',
          placement: 'Frente e Costas',
          notes: 'Monograma dos noivos dourado com nomes dos padrinhos individual.',
        },
      },
      {
        id: 'qitem-2',
        productId: 'prod-3',
        productName: 'Boné Trucker Personalizado Americano com Tela',
        productImage: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&w=400&q=80',
        colorName: 'Preto',
        colorHex: '#111827',
        sizeName: 'Tamanho Único',
        quantity: 30,
        unitPrice: 26.0,
        subtotal: 780.0,
        customization: {
          customText: '#CasamentoM&L',
          placement: 'Frente',
        },
      },
    ],
    subtotal: 1775.0,
    discount: 100.0,
    shipping: 45.0,
    total: 1720.0,
    status: 'enviado',
    notes: 'Validade do orçamento: 15 dias. Desconto especial aplicado para lote de casamento.',
    expiresAt: '2026-09-05T23:59:59.000Z',
    createdAt: '2026-08-16T11:00:00.000Z',
  },
  {
    id: 'orc-2',
    quoteNumber: 'ORC-000002',
    customerId: 'cust-2',
    customerName: 'Ana Paula Rocha (Academia IronFit)',
    customerPhone: '(11) 96543-2109',
    customerWhatsapp: '11965432109',
    customerEmail: 'anapaula@ironfit.com.br',
    items: [
      {
        id: 'qitem-3',
        productId: 'prod-2',
        productName: 'Moletom Canguru Premium Flanelado com Capuz',
        productImage: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=400&q=80',
        colorName: 'Preto',
        colorHex: '#111827',
        sizeName: 'G',
        quantity: 15,
        unitPrice: 78.0,
        subtotal: 1170.0,
        customization: {
          customText: 'IRONFIT STAFF',
          placement: 'Costas',
        },
      },
    ],
    subtotal: 1170.0,
    discount: 70.0,
    shipping: 0.0,
    total: 1100.0,
    status: 'aprovado',
    notes: 'Cliente aprovou via WhatsApp. Aguardando emissão da fatura para conversão.',
    expiresAt: '2026-09-01T23:59:59.000Z',
    createdAt: '2026-08-17T15:30:00.000Z',
  },
];

export const INITIAL_LOGS: ActivityLog[] = [
  {
    id: 'log-1',
    userId: 'usr-admin-1',
    userName: 'Maurício (Admin)',
    action: 'Alterou status do pedido',
    details: 'Pedido PED-000101 alterado de "Arte Aprovada" para "Em Produção"',
    targetType: 'order',
    targetId: 'ord-101',
    timestamp: '2026-08-18T08:00:00.000Z',
  },
  {
    id: 'log-2',
    userId: 'usr-admin-1',
    userName: 'Maurício (Admin)',
    action: 'Criou orçamento',
    details: 'Criou orçamento ORC-000001 para cliente Mariana Costa (R$ 1.720,00)',
    targetType: 'quote',
    targetId: 'orc-1',
    timestamp: '2026-08-16T11:00:00.000Z',
  },
  {
    id: 'log-3',
    userId: 'usr-admin-1',
    userName: 'Maurício (Admin)',
    action: 'Cadastrou produto',
    details: 'Cadastrou novo produto: Camiseta Personalizada Dry Fit UV50+',
    targetType: 'product',
    targetId: 'prod-1',
    timestamp: '2026-08-01T10:00:00.000Z',
  },
];
